title: "Héctor L. Torres Vera"
author: 
  name: "Héctor L. Torres Vera"
  email: "torresvera.hl [at] gmail.com"

description: "Biochemist, Science Writer, and Communicator"

url: "https://hltorresvera.github.io"
# theme: minima
remote_theme: "jekyll/minima@1e8a445"

# minima settings
minima:

  #skin
  skin: classic

  #nav
  nav_pages:
    - index.md
    - resume.md
    - writing.md
