title: Héctor L. Torres Vera
author: 
  email: torresvera.hl [at] gmail.com

description: Biochemist, Science Writer, and Communicator

url: https://hltorresvera.github.io

# theme: minima
remote_theme: jekyll/minima@59f9a68

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# minima settings
minima:
  skin: classic
minima:
  nav_pages:
    - index.md
    - resume.md
    - writing.md

