title: Héctor L. Torres Vera
author: 
  email: torresverahl [at] gmail.com

description: Biochemist, Science Writer, and Communicator

url: https://www.hltorresvera.com
baseurl: ""

# theme: minima
remote_theme: jekyll/minima@59f9a68

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# minima settings
minima:
  skin: classic
minima:
  nav_pages:
    - about.md  
    - resume.md  
    - writing.md  

