title: "Héctor L. Torres Vera"
description: "Biochemist, Science Writer, and Communicator"
baseurl: ""
url: "https://hltorresvera.github.io"
theme: minima

# Navigation
header_pages:
  - index.md
  - work.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown

