title: "Héctor L. Torres Vera"
author: "HLTV"
description: "Biochemist, Science Writer, and Communicator"
baseurl: ""
url: "https://hltorresvera.github.io"
remote_theme: "jekyll/minima@1e8a445"

# Navigation
header_pages:
  - index.md
  - resume.md
  - writing.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown

